apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi # dummy, size is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" #starage class should be empty in static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d1813099393cb540 # this should be taken from the fisle system we created
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-static
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
    # here we are giving az which we are selecting the az in the volume 
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-static
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-lb
# spec:
#   type: LoadBalancer
#   selector:
#     project: roboshop
#     component: frontend
#     environment: dev
#     purpose: efs-static # same in pod label
#   ports:
#     - protocol: TCP
#       port: 80 # service port
#       targetPort: 80 # container port
#       nodePort: 30007 